name: Pre

on:
  schedule:
    - cron:  '30 5 * * *'
  workflow_dispatch:

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    outputs:
      valid: ${{ steps.checksum.outputs.is_valid }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Get sha512sums from PKGBUILD
        id: sha512
        run: echo "::set-output name=sha512sums::$(sed -n '/sha512sums=("/{s/.*sha512sums=("//;s/\").*//;p}' PKGBUILD)"

      - name: Verify checksum with upstream
        id: checksum
        run: |
          wget https://github.com/yamatsum/nonicons/raw/master/dist/nonicons.ttf
          sha512sum nonicons.ttf | 
          while read -r sum _ ; do 
            [[ $sum == ${{ steps.sha512.outputs.sha512sums }} ]] && echo "::set-output name=is_valid::true" || echo "::set-output name=is_valid::false"
          done

  build:
    name: Build
    needs: check
    if: needs.check.outputs.valid == 'false'
    runs-on: ubuntu-latest
    container:
      image: archlinux:base-devel
      options: --privileged
      volumes:
        - /sys/fs/cgroup:/sys/fs/cgroup

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install dependencies
        run: pacman -Syu --needed --noconfirm git wget sudo

      - name: Setup sudo user & permission
        run: |
          useradd -m mas
          usermod -aG wheel mas
          echo 'wheel  ALL=(ALL:ALL) ALL' >> /etc/sudoers
          chown -R mas $GITHUB_WORKSPACE

      - name: Get upstream git hash
        id: get-hash
        run: |
          git clone https://github.com/yamatsum/nonicons.git
          cd nonicons
          echo "::set-output name=hash::$(printf "r%s.%s" "$(git rev-list --count HEAD)" "$(git rev-parse --short HEAD)")"

      - name: Get upstream sha512 hash
        id: get-sha512
        run: |
          wget https://github.com/yamatsum/nonicons/raw/master/dist/nonicons.ttf
          echo "::set-output name=hash::$(sha512sum nonicons.ttf | cut -f 1 -d " ")"

      - name: Update git hash based version on PKGBUILD
        run: sed -i 's:^pkgver=.*$:pkgver=${{ steps.get-hash.outputs.hash }}:g' PKGBUILD

      - name: Update checksums on PKGBUILD
        run: sed -i 's:^sha512sums=.*$:sha512sums=("${{ steps.get-sha512.outputs.hash }}"):g' PKGBUILD

      - name: Generate new .SRCINFO
        run: sudo -u mas makepkg --printsrcinfo > .SRCINFO

      - name: Push changes
        run: |
          cd $GITHUB_WORKSPACE
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add PKGBUILD .SRCINFO 
          git commit -m "Update package"
          git push

      - name: Trigger CI workflow
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: CI
          token: ${{ secrets.PERSONAL_TOKEN }}

